server:
  port: 8082
  servlet:
    context-path: /pic_api
logging:
  level:
    root: INFO

file:
  staticAccessPath: /img/**
  uploadFolder: G://xiazai/
  filePrefix: http://localhost:8082/pic_api/img/