spring:
  profiles:
    active: dev
  datasource:
      url: jdbc:mysql://localhost:3306/pic_db?useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
  servlet:
    multipart:
      max-file-size: 10Mb

mybatis:
    type-aliases-package: com.im.pojo
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers: com.im.utils.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql