server:
  port: 8080
  servlet:
    context-path: /pic_api
logging:
  level:
    root: INFO

file:
  staticAccessPath: /img/**
  uploadFolder: /var/local/pic_api/imgs/
  filePrefix: http://120.79.82.1:8080/pic_api/img/